### PR TITLE
Various changes to the cryptomator build process:

### PR DESCRIPTION
**Pull request by overheadhunter**
- The package build is now based on "antkit.tar.gz" instead of the fat jar "Cryptomator-x.z.y.jar".
- Updated version to 1.1.0
- Added desktop entry + icon file
- Added mime type registration
- Depend on OpenJRE 8, as Cryptomator doesn't run on Java 7
- Added build dependency: Ant
- Installing .jar files with 644 rights

### CODE REVIEW

**Comment by Foxboron** [comment]
``` diff
diff --git a/cryptomator/PKGBUILD b/cryptomator/PKGBUILD
index 0cc3ef7..013b491 100644
--- a/cryptomator/PKGBUILD
+++ b/cryptomator/PKGBUILD
@@ -8,14 +8,15 @@ pkgdesc="Multiplatform transparent client-side encryption of your files in the c
 arch=("any")
 url="https://cryptomator.org/"
 license=('MIT/X Consortium License')
-depends=('jre8-openjdk' 'java-openjfx')
+depends=('java-runtime=8' 'java-openjfx')
 makedepends=('apache-ant')
+optdepends=('rng-tools: Entropy generation')
 source=("antkit-${pkgver}.tar.gz::https://github.com/cryptomator/cryptomator/releases/download/${pkgver}/antkit.tar.gz"
         'cryptomator.sh'
         'cryptomator.desktop'
         'cryptomator-vault.xml')
 sha256sums=('SKIP'
-            '0bc12ee603ef87536389aeb85bf0afaf8995bae2c9ed826290b2bb0d838a9766'
+            '031fbf7f62fe27d496c42f71818e19aa9d4a9920df3228ac032bb795e81c30b7'
             '1193f85b545298f6d474c7f17865433f25c73995b00894e0d7d7bc873c696464'
             '78537ead26dcc1488d7fff02f47fce559f70f9bb2d7fa7fa1741ad3cd151bfad')

@@ -23,6 +24,7 @@ build() {
   export JAVA_HOME=/usr/lib/jvm/default-runtime/
   ant create-jar
 }
+
 package() {
   install -d ${pkgdir}/usr/share/java/${pkgname}
   install -Dm644 ${srcdir}/libs/*.jar ${pkgdir}/usr/share/java/$pkgname
@@ -32,10 +34,12 @@ package() {
   install -Dm644 ${srcdir}/cryptomator-vault.xml ${pkgdir}/usr/share/mime/packages/cryptomator-vault.xml
   install -Dm644 ${srcdir}/cryptomator.desktop ${pkgdir}/usr/share/applications/cryptomator.desktop
 }
+
 post_install() {
   xdg-desktop-menu install --novendor /usr/share/applications/cryptomator.desktop
   xdg-mime install /usr/share/mime/packages/cryptomator-vault.xml
 }
+
 pre_remove() {
   xdg-desktop-menu uninstall --novendor /usr/share/applications/cryptomator.desktop
   xdg-mime uninstall /usr/share/mime/packages/cryptomator-vault.xml
diff --git a/cryptomator/cryptomator.sh b/cryptomator/cryptomator.sh
index 090d528..95f8b15 100644
--- a/cryptomator/cryptomator.sh
+++ b/cryptomator/cryptomator.sh
@@ -1,2 +1,3 @@
 #!/bin/sh
-exec /usr/bin/java -jar '/usr/share/java/cryptomator/cryptomator.jar' "$@"
+export PATH=/usr/lib/jvm/java-8-openjdk/jre/bin/:$PATH
+exec java -jar '/usr/share/java/cryptomator/cryptomator.jar' "$@"
```

Some suggested changes:
Added back rng-tools for entropy generation as optional dependency.  
Removed the explicit `jre8-openjdk` for `java-runtime=8` and override the default java for java8 to avoid problems with the script. 

Im unsure if setting `JAVA_HOME` too the default runtime is enough? People might still have java7 set as default and the build would fail. Should we just point it too `java-8-openjdk`? Unsure what is best practice here.

If this looks OK i'll regenerate the srcinfo file and merge.

**Comment by overheadhunter** [comment]
I don't support adding rng-tools. This was a temporary workaround for debugging (and only for debugging), as the RNG is not cryptographically suitable. The entropy shortage has been fixed with Cryptomator 1.0.3 ([see discussion](https://github.com/cryptomator/cryptomator/issues/174)), so this dependency is neither secure nor required.

But I'm fine with everything else, use java-8-openjdk path in `build()` section.

If using `java-runtime=8`, we should however use a generic path in the launcher shell script, too.

**Comment by overheadhunter** [comment]
Oh and I just noticed, that `apache-ant` depends on either jdk. I think we should add `jdk8-openjdk` to `makedepends`.

**Comment by Foxboron** [comment]
Right, the `rng-tools` was suggested on AUR and i added it without a second guess.
I think `java-runtime=8` should work inn `makedepends`? AFAIK its just a virtual dependency to provide the java dependencies for Arch

**Comment by overheadhunter** [comment]
I think we need the JDK, not the JRE during build.

**Comment by Foxboron** [comment]
Merged and pushed too AUR \o/

**Pull request merged**
